FROM cuda10-ompl

COPY requirements.txt /root/.
WORKDIR /root
RUN apt-get update && apt-get install -y git
RUN pip3 install -r requirements.txt

RUN git clone --recurse-submodules https://github.com/jacobjj/sparse_rrt.git
WORKDIR /root/sparse_rrt
RUN pip3 install -e /root/sparse_rrt
RUN apt-get install -y libcairo-dev

RUN pip3 install opencv-python \
				cairosvg

RUN apt-get install -y python3-pyqt5

CMD [bash]